// Kab/kota geometry loader + SVG projection helpers for the choropleth.
// Files generated by scripts/build_geo.py into public/geo/prov-<kode>.json.

const geoCache = new Map();

export async function loadProvinceGeo(provKode) {
  const key = String(provKode).slice(0, 2);
  if (geoCache.has(key)) return geoCache.get(key);
  const promise = fetch(`${import.meta.env.BASE_URL}geo/prov-${key}.json`)
    .then((res) => {
      if (!res.ok) throw new Error(`geo ${key}: HTTP ${res.status}`);
      return res.json();
    })
    .catch((err) => {
      geoCache.delete(key); // allow retry on transient failure
      throw err;
    });
  geoCache.set(key, promise);
  return promise;
}

// Province-level geometry for the national choropleth
// (generated by scripts/build_national_geo.py).
export async function loadNationalGeo() {
  const key = '__national__';
  if (geoCache.has(key)) return geoCache.get(key);
  const promise = fetch(`${import.meta.env.BASE_URL}geo/indonesia-provinces.json`)
    .then((res) => {
      if (!res.ok) throw new Error(`geo nasional: HTTP ${res.status}`);
      return res.json();
    })
    .catch((err) => {
      geoCache.delete(key);
      throw err;
    });
  geoCache.set(key, promise);
  return promise;
}

// ── Projection: equirectangular fitted to the collection bbox ──

function eachPoint(geometry, fn) {
  const walk = (coords) => {
    if (typeof coords[0] === 'number') fn(coords);
    else coords.forEach(walk);
  };
  walk(geometry.coordinates);
}

export function makeProjection(features, width, height, pad = 8) {
  let minLon = Infinity, maxLon = -Infinity, minLat = Infinity, maxLat = -Infinity;
  features.forEach((ft) => eachPoint(ft.geometry, ([lon, lat]) => {
    if (lon < minLon) minLon = lon;
    if (lon > maxLon) maxLon = lon;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }));
  if (!isFinite(minLon)) return null;

  const midLat = (minLat + maxLat) / 2;
  const kx = Math.cos((midLat * Math.PI) / 180);
  const spanX = (maxLon - minLon) * kx || 1e-9;
  const spanY = (maxLat - minLat) || 1e-9;
  const scale = Math.min((width - pad * 2) / spanX, (height - pad * 2) / spanY);
  const ox = (width - spanX * scale) / 2;
  const oy = (height - spanY * scale) / 2;

  return ([lon, lat]) => [
    ox + (lon - minLon) * kx * scale,
    oy + (maxLat - lat) * scale,
  ];
}

export function geometryToPath(geometry, project) {
  const ring = (coords) => {
    let d = '';
    for (let i = 0; i < coords.length; i++) {
      const [x, y] = project(coords[i]);
      d += (i === 0 ? 'M' : 'L') + x.toFixed(1) + ' ' + y.toFixed(1);
    }
    return d + 'Z';
  };
  if (geometry.type === 'Polygon') return geometry.coordinates.map(ring).join('');
  if (geometry.type === 'MultiPolygon') {
    return geometry.coordinates.map((poly) => poly.map(ring).join('')).join('');
  }
  return '';
}
